# Generated by Django 4.1.2 on 2022-10-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='created',
        ),
        migrations.RemoveField(
            model_name='template',
            name='css',
        ),
        migrations.RemoveField(
            model_name='template',
            name='html',
        ),
        migrations.RemoveField(
            model_name='template',
            name='image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='javascript',
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javascript', models.FileField(upload_to='js')),
                ('css', models.FileField(upload_to='css')),
                ('html', models.FileField(upload_to='html')),
                ('image', models.ImageField(upload_to='img')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.template')),
            ],
        ),
    ]
