# Generated by Django 4.1.2 on 2022-10-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_templatecssfile_templatejsfile_delete_templatefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatecssfile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='templatecssfile',
            name='html',
        ),
        migrations.RemoveField(
            model_name='templatecssfile',
            name='image',
        ),
        migrations.CreateModel(
            name='TemplateIMGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateHTMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.FileField(upload_to='html')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.template')),
            ],
        ),
    ]
